CB_app/urls.py
from django.conf.urls import url
from django.urls import path
from CB_app import views

app_name = 'CB_app'

urlpatterns = [
    path('',views.customerListView.as_view(),name='customer'),
    path('<int:pk>/',views.customerDetailView.as_view(),name='detail'),
    path('create/',views.customercreateview.as_view(),name='create'),
    path('update/<int:pk>/',views.customerupdateview.as_view(),name='update'),
    path('delete/<int:pk>/',views.customerdeleteview.as_view(),name='delete'),

    path('bookmark/',views.bookmarkListView.as_view(),name='bookmark'),
    path('bookmark/<int:pk>/',views.bookmarkDetailView.as_view(),name='b_detail'),
    path('bookmark/b_create/',views.bookmarkcreateview.as_view(),name='b_create'),
    path('bookmark/b_update/<int:pk>/',views.bookmarkupdateview.as_view(),name='b_update'),
    path('bookmark/b_delete/<int:pk>/',views.bookmarkdeleteview.as_view(),name='b_delete'),

    path('query/',views.Query.as_view(),name = 'query'),


]

customerbookmark/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.conf.urls import url, include
from CB_app import views

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^app/',include('CB_app.urls',namespace = 'CB_app')),
    path('admin/', admin.site.urls),
]

CB_app/models.py
from django.db import models
from django.urls import reverse

class customer_profile(models.Model):
    customer_fname = models.CharField(max_length = 50)
    customer_lname = models.CharField(max_length = 50)
    lat = models.CharField(max_length = 50)
    lon = models.CharField(max_length = 50)

    def __str__(self):
        return self.customer_fname +' '+ self.customer_lname
    def get_absolute_url(self):
        return reverse("CB_app:detail",kwargs={'pk':self.pk})

class Bookmark(models.Model):
    title = models.CharField(max_length = 75)
    url = models.URLField(max_length = 200)
    source_name = models.CharField(max_length = 50)
    pub_date = models.DateField()
    customer = models.ManyToManyField(customer_profile, through='customer_bookmark')

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("CB_app:b_detail",kwargs={'pk':self.pk})

class customer_bookmark(models.Model):
    cb_customer_id = models.ForeignKey(customer_profile, related_name = 'cb_customer_ids',on_delete=models.CASCADE)
    cb_bookmark_id = models.ForeignKey(Bookmark, related_name = 'cb_bookmark_ids',on_delete=models.CASCADE)

CB_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from CB_app import models
from CB_app.models import customer_profile,Bookmark,customer_bookmark
from django.views.generic.edit import (CreateView,DeleteView,UpdateView)
from django.views.generic import View,TemplateView,ListView,DetailView

from django.db.models import Q

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class customerListView(ListView):
    model = customer_profile

class customerDetailView(DetailView):
    context_object_name = 'cust_dv'
    model = customer_profile
    template_name = 'CB_app/customer_detailview.html'

class customercreateview(CreateView):

    fields = ('customer_fname','customer_lname','lat','lon')
    model = customer_profile


class customerupdateview(UpdateView):
    fields = ('customer_fname','customer_lname')
    model = customer_profile

class customerdeleteview(DeleteView):
    model = customer_profile
    success_url = reverse_lazy("CB_app:customer")


class bookmarkListView(ListView):
    model = Bookmark

class bookmarkDetailView(DetailView):
    context_object_name = 'bdv'
    model = Bookmark
    template_name = 'CB_app/bookmark_detailview.html'

class bookmarkcreateview(CreateView):
    fields = ('title','url','source_name','pub_date','customer')
    model = Bookmark

class bookmarkupdateview(UpdateView):
    fields = ('title','url')
    model = Bookmark

class bookmarkdeleteview(DeleteView):
    model = Bookmark
    success_url = reverse_lazy("CB_app:bookmark")


class Query(TemplateView):
    template_name = 'CB_app/query.html'
    def get(self,request):
        query = models.customer_bookmark.objects.all().select_related('cb_customer_id').select_related('cb_bookmark_id')
        q = request.GET.get('q')
        if q != '' and q is not None:
            query = query.filter(cb_customer_id__customer_fname__icontains=q) \
                 | query.filter(cb_customer_id__customer_lname__icontains=q)  \
                 | query.filter(cb_bookmark_id__source_name__icontains=q) \
                 | query.filter(cb_customer_id__id__icontains=q) \
                 | query.filter(cb_bookmark_id__id__icontains=q)

        return render(request, self.template_name, {'query':query})

CB_app/templates/CB_app/bookmark_confirm_delete.html
{% extends "base.html" %}
{% block body_block %}

    <h1> Do you want to delete this bookmark title : {{bookmark.title}} ?</h1>
    <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a class="btn btn-secondary" href={% url 'CB_app:bookmark' %}>Cancel</a>

  </form>
{% endblock %}

CB_app/templates/CB_app/bookmark_detailview.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the Bookmark Detail Page</h1>
    <p>Id_num: {{bdv.id}}</p>
    <p>Title: {{bdv.title}}</p>
    <p>URL: {{bdv.url}}</p>
    <p>Source Name: {{bdv.source_name}}</p>
    <p>Publish Date: {{bdv.pub_date}}</p>
    <a class='btn btn-warning' href="{% url 'CB_app:b_update' pk=bdv.pk %}">Update </a>
    <a class='btn btn-danger' href="{% url 'CB_app:b_delete' pk=bdv.pk %}">Delete </a>
    <a class="btn btn-secondary" href={% url 'CB_app:bookmark' %}>Cancel</a>

  </div>
{% endblock %}

CB_app/templates/CB_app/bookmark_form.html
{% extends "base.html" %}

{% block body_block %}
<h1>
  hello this is book mark page
  {% if not form.instance.pk %}
  Create Bookmark
  {% else %}
  Update Bookmark
  {% endif %}

</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="ADD">
    <a class="btn btn-secondary" href={% url 'CB_app:bookmark' %}>Cancel</a>
  </form>
{% endblock %}

CB_app/templates/CB_app/bookmark_list.html
{% extends "base.html" %}

{% block body_block %}

<h1>Welcome to Bookmark models page</h1>
<p>number of Bookmarks = {{bookmark_list|length}}</p>

<table class="table table-dark table-striped">
      <tr>
          <th>Bookmark ID</th>
          <th>Title</th>
          <th>URL</th>
          <th>Source</th>
          <th>Publish Date</th>

      </tr>
    {% for bookmark in bookmark_list %}
      <tr>
          <td><a href="{{bookmark.id}}">{{ bookmark.id }}</a></td>
          <td>{{ bookmark.title }}</td>
          <td><a href="{{ bookmark.url }}">{{ bookmark.url }}</a></td>
          <td>{{ bookmark.source_name }}</td>
          <td>{{ bookmark.pub_date }}</td>
      </tr>
    {% endfor %}
    </table>

    <div class="container">
    <a class='btn btn-primary' href="{% url 'CB_app:b_create' %}">Add Bookmark</a>

  </div>
{% endblock %}

CB_app/templates/CB_app/customer_detailview.html
{% extends "base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the Customer Detail Page</h1>
    <p>Id_num: {{cust_dv.id}}</p>
    <p>First_Name: {{cust_dv.customer_fname}}</p>
    <p>Last_Name: {{cust_dv.customer_lname}}</p>
    <p>Latitude: {{cust_dv.lat}}</p>
    <p>Longitude: {{cust_dv.lon}}</p>
    <a class='btn btn-warning' href="{% url 'CB_app:update' pk=cust_dv.pk %}">Update </a>
    <a class='btn btn-danger' href="{% url 'CB_app:delete' pk=cust_dv.pk %}">delete </a>
    <a class="btn btn-secondary" href={% url 'CB_app:customer' %}>Cancel</a>
  </div>

{% endblock %}

CB_app/templates/CB_app/customer_profile_confirm_delete.html
{% extends "base.html" %}
{% block body_block %}

    <h1> Do you want to delete {{customer_profile.customer_fname}} {{customer_profile.customer_lname}} ?</h1>
    <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a class="btn btn-secondary" href={% url 'CB_app:customer' %}>Cancel</a>

  </form>
{% endblock %}

CB_app/templates/CB_app/customer_profile_form.html
{% extends "base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create Customer
  {% else %}
  Update Customer
  {% endif %}

</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="ADD">
    <a class="btn btn-secondary" href={% url 'CB_app:customer' %}>Cancel</a>
  </form>
{% endblock %}

CB_app/templates/CB_app/customer_profile_list.html
{% extends "base.html" %}

{% block body_block %}

<h1>Welcome to customer profiles page</h1>
<p>number of customers = {{customer_profile_list|length}}</p>
<table class="table table-dark table-striped">
      <tr>
          <th>Customer ID</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Latitude</th>
          <th>Longitude</th>

      </tr>
    {% for customer in customer_profile_list %}
      <tr>
          <td><a href="{{customer.id}}">{{ customer.id }}</a></td>
          <td>{{ customer.customer_fname }}</td>
          <td>{{ customer.customer_lname }}</td>
          <td>{{ customer.lat }}</td>
          <td>{{ customer.lon }}</td>
      </tr>
    {% endfor %}
    </table>
    <div class="container">
    <p><a class='btn btn-primary' href="{% url 'CB_app:create' %}">Add Customer</a></p>

  </div>

{% endblock %}

CB_app/templates/CB_app/query.html
{% extends "base.html" %}

{% block body_block %}
<p> This is from Customer Bookmark table </p>

<form method="get" action=".">
  {% csrf_token %}
  <input type="text" name="q" placeholder="Search">
  <input type="submit" value="Search">
  <table class="table table-dark table-striped table table-bordered">
        <tr class="table-success">
            <th>Customer ID</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Latitude</th>
            <th>Longitude</th>
            <th>Bookmark ID</th>
            <th>Title</th>
            <th>URL</th>
            <th>Source</th>
            <th>Publish Date</th>

        </tr>
      {% for customer in query %}
        <tr>
            <td>{{ customer.cb_customer_id.id }}</td>
            <td>{{ customer.cb_customer_id.customer_fname }}</td>
            <td>{{ customer.cb_customer_id.customer_lname }}</td>
            <td>{{ customer.cb_customer_id.lat }}</td>
            <td>{{ customer.cb_customer_id.lon }}</td>
            <td>{{ customer.cb_bookmark_id.id }}</td>
            <td>{{ customer.cb_bookmark_id.title }}</td>
            <td>{{ customer.cb_bookmark_id.url }}</td>
            <td>{{ customer.cb_bookmark_id.source_name }}</td>
            <td>{{ customer.cb_bookmark_id.pub_date }}</td>


        </tr>
      {% endfor %}
      </table>
      <p>number of Customer Bookmark = {{query|length}}</p>

</form>



{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <style>
        h1 {
          color:Tomato;
          text-align: center;
        }
        h6 {
          color:white;
          text-align: left;
        }
        th,tr {
          color:black;
          text-align: center;
        }
        p {
          font-family: verdana;
          font-size: 20px;
        }
  </style>
  </head>
  <body style="background-color:grey;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <a class="nav-item nav-link" href={% url 'CB_app:customer' %}>Customer Details</a>
        <a class="nav-item nav-link" href={% url 'CB_app:bookmark' %}>Bookmark Details</a>
        <a class="nav-item nav-link" href={% url 'CB_app:query' %}>Customer Bookmark Details</a>
        </div>
        <div class="navbar-nav align-items-center ml-auto">
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>

    <div class="container">

        {% block body_block %}

        {% endblock %}


    </div>



  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
  integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block body_block %}
<h1>This is Home page</h1>
<h5>This is a sample customer bookmark project</h5>
<p>
In this customer bookmark project I have created three models called
</p>
  <ol>
    <li>customer_profile</li>
    <li>Bookmark</li>
    <li>customer_bookmark</li>
  </ol>

  <p>
    In the navbar we have all three model details <br>
    In the first two models we have option to do CRUD(Create, Read, Update and Delete) operations <br>
    In the third model we have first two tables records along with that search option, <br>
    The search option will retrieve records from the table what you want exactly. <br>
    The final option we have admin on the right side of navbar feel free to login superuser <br>
    Username : Admin <br>
    Password : password <br>
   </p>


<h6>In the customer_profile model</h6>

  we have given four fileds called

<ul>
  <li>customer_fname</li>
  <li>customer_lname</li>
  <li>lat (Latitude)</li>
  <li>lon (Longitude)</li>
</ul>

<h6>In the Bookmark model</h6>

  we have given five fileds called

<ul>
  <li>Title</li>
  <li>URL</li>
  <li>source_name</li>
  <li>pub_date</li>
  <li>customer (ManyToManyField)</li>
</ul>
<h6>In the customer_bookmark model</h6>

  we have given two fileds called

<ul>
  <li>cb_customer_id (ForeignKey)</li>
  <li>cb_bookmark_id (ForeignKey)</li>
</ul>



{% endblock %}